
<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Master_Tims extends CI_Controller
{

  function __construct()
  {
    parent::__construct();

    $this->load->model(array('M_Tims', 'm_tims', 'M_gen_master','M_vcdn'));
    $this->load->library(array('template', 'user_agent'));

    if (!$this->session->userdata('userid_1')) {
      redirect('login');
    }
  }

  /* -------------------------------------------------------------------------- */
  /*                                Master Driver                               */
  /* -------------------------------------------------------------------------- */

  public function driver()
  {
    $data['drivers'] =  $this->m_tims->drivers();
    $this->template->display('shipping/Tims/driver/index', $data);
  }

  public function driver_add()
  {
    $data = [
      'header_title'    => 'Form Add Driver',
      'info'            => '<small class="text-danger">Please copy this password before save. because the system will encrypt password, after save you cannot see the password again.</small>',
      'action'          => site_url('Master_Tims/driver-save'),
      'button'          => 'Save',
      'driver_name'     => set_value('driver_name', '', true),
      'driver_loginid'  => set_value('driver_loginid', 'Automatic Generated By System', true),
      'driver_loginpass'  => set_value('driver_loginpass', rand(1000, 9999), true),
      'driver_type'     => set_value('driver_type', '', true),
      'psa_pass_number' => set_value('psa_pass_number', '', true),
      'psa_pass_exp'    => set_value('psa_pass_exp', '', true),
      'psa_pin'         => set_value('psa_pin', '', true),
      'diesel_pin'      => set_value('diesel_pin', '', true),
      'handset_no'      => set_value('handset_no', '', true),
      'license_exp'     => set_value('license_exp', '', true),
    ];

    $this->template->display('shipping/Tims/driver/form', $data);
  }

  public function driver_save()
  {
    $data = $this->input->post(null, true);

    $username = explode(' ', $data['driver_name']);
    $rand = rand(100, 999);

    $data['driver_loginid']   = $username[0] . $rand;
    $data['driver_loginpass'] = md5(sha1($data['driver_loginpass']));
    $data['psa_pass_exp']     = convert_tgl_db_2($data['psa_pass_exp']);
    $data['license_exp']      = convert_tgl_db_2($data['license_exp']);
    $data['created_by']       = strtoupper($this->session->userdata('userid_1'));
    $data['created_date']     = date('Y-m-d H: i: s');

    $save = $this->m_tims->save_driver($data);

    if (!$save) {
      $this->session->set_flashdata('message', pesan('Save Driver', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Add Driver', pesan_sukses()));
    }
    redirect(site_url('Master_Tims/driver-add'));
  }

  public function driver_edit($id)
  {
    $driver = $this->m_tims->driver_by_id($id);

    if (!$driver) {
      redirect(site_url('Master_Tims/driver-add'));
    }

    $data = [
      'header_title'    => 'Form Edit Driver',
      'info'            => '<small class="text-danger">Input Password if want to Reset, leave it blank if not want to reset password</small>',
      'action'          => site_url('Master_Tims/driver-update/' . $id),
      'button'          => 'Update',
      'driver_loginid'  => set_value('driver_name', $driver->driver_loginid, true),
      'driver_loginpass'  => set_value('driver_loginpass', '', true),
      'driver_name'     => set_value('driver_name', $driver->driver_name, true),
      'driver_type'     => set_value('driver_type', $driver->driver_type, true),
      'psa_pass_number' => set_value('psa_pass_number', $driver->psa_pass_number, true),
      'psa_pass_exp'    => set_value('psa_pass_exp', tgl_dmy($driver->psa_pass_exp), true),
      'psa_pin'         => set_value('psa_pin', $driver->psa_pin, true),
      'diesel_pin'      => set_value('diesel_pin', $driver->diesel_pin, true),
      'handset_no'      => set_value('handset_no', $driver->handset_no, true),
      'license_exp'     => set_value('license_exp', tgl_dmy($driver->license_exp), true),
    ];

    $this->template->display('shipping/Tims/driver/form', $data);
  }

  public function driver_update($id)
  {
    $data = $this->input->post(null, true);

    if ($data['driver_loginpass'] != '') {
      $data['driver_loginpass'] = md5(sha1($data['driver_loginpass']));
    } else {
      unset($data['driver_loginpass']);
    }

    $data['psa_pass_exp'] = convert_tgl_db_2($data['psa_pass_exp']);
    $data['license_exp'] = convert_tgl_db_2($data['license_exp']);
    $data['updated_by'] = strtoupper($this->session->userdata('userid_1'));
    $data['updated_date'] = date('Y-m-d H:i:s');
    $update = $this->m_tims->update_driver($data, $id);

    if (!$update) {
      $this->session->set_flashdata('message', pesan('Update Driver', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Update Driver', pesan_sukses()));
    }
    redirect(site_url('Master_Tims/driver-edit/' . $id));
  }

  public function driver_delete($id)
  {
    $delete = $this->m_tims->driver_delete($id);

    if (!$delete) {
      $this->session->set_flashdata('message', pesan('Delete Driver', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Delete Driver', pesan_sukses()));
    }
    redirect(site_url('Master_Tims/driver'));
  }

  /* -------------------------------------------------------------------------- */
  /*                              End Master Driver                             */
  /* -------------------------------------------------------------------------- */


  /* -------------------------------------------------------------------------- */
  /*                                Master Price                               */
  /* -------------------------------------------------------------------------- */


  public function price()
  {
    $data['prices'] =  $this->m_tims->prices();
    $this->template->display('shipping/Tims/prices/index', $data);
  }


  public function price_add()
  {
    $data = [
      'header_title'    => 'Driver Prices',
      'action'          => site_url('Master_Tims/save_price'),
      'button'          => 'Save',
      'driver_wages'    => set_value('driver_wages', '', true),
      'local_pertrip'   => set_value('local_pertrip', '', true),
      'prc_pertrip'     => set_value('prc_pertrip', '', true),
      'extra_trip'      => set_value('extra_trip', '', true),
    ];

    $this->template->display('shipping/Tims/prices/form', $data);
  }

  public function save_price()
  {
    $data = $this->input->post(null, true);
    $data['createdby'] = strtoupper($this->session->userdata('userid_1'));
    $data['createddate'] = date('Y-m-d H:i:s');

    $save = $this->m_tims->save_price($data);

    if (!$save) {
      $this->session->set_flashdata('message', pesan('Save Price', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Add Price', pesan_sukses()));
    }
    redirect(site_url('Master_Tims/price-add'));
  }

  public function price_edit($id)
  {
    $price = $this->m_tims->price_by_id($id);

    if (!$price) {
      redirect(site_url('Master_Tims/price-add'));
    }

    $data = [
      'header_title'    => 'Form Edit Price',
      'action'          => site_url('Master_Tims/price-update/' . $id),
      'button'          => 'Update',
      'driver_wages'    => set_value('driver_wages', $price->driver_wages, true),
      'local_pertrip'   => set_value('local_pertrip', $price->local_pertrip, true),
      'prc_pertrip'     => set_value('prc_pertrip', $price->prc_pertrip, true),
      'extra_trip'      => set_value('extra_trip', $price->extra_trip, true),
    ];

    $this->template->display('shipping/Tims/prices/form', $data);
  }

  public function price_update($id)
  {
    $data = $this->input->post(null, true);

    $data['updatedby'] = strtoupper($this->session->userdata('userid_1'));
    $data['updateddate'] = date('Y-m-d H:i:s');
    $update = $this->m_tims->update_price($data, $id);

    if (!$update) {
      $this->session->set_flashdata('message', pesan('Update Price', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Update Price', pesan_sukses()));
    }
    redirect(site_url('Master_Tims/price-edit/' . $id));
  }

  public function price_delete($id)
  {
    $delete = $this->m_tims->price_delete($id);

    if (!$delete) {
      $this->session->set_flashdata('message', pesan('Delete Price', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Delete Price', pesan_sukses()));
    }
    redirect(site_url('Master_Tims/price'));
  }



  /* -------------------------------------------------------------------------- */
  /*                              End Master Price                             */
  /* -------------------------------------------------------------------------- */


  /* -------------------------------------------------------------------------- */
  /*                               Master Vehicle                               */
  /* -------------------------------------------------------------------------- */

  function vehicle_information()
  {
    $data['title'] = 'Vehicle Information List';
    $data['List_Vehicle']   = $this->M_Tims->get_vehicle();
    $this->template->display('shipping/Tims/vehicle/vehicle_information', $data);
  }
  public function vehicle_detail()
  {
    $param = $this->input->get();
    $data = $this->m_tims->get_item_vehicle($param['id']);
    $data->insurance_cost = number_format($data->insurance_cost, 2);
    echo json_encode($data);
  }

  function vehicle_input()
  {
    $vehicle_types = ['Goods(Open) Prime Mover', 'Trailers'];
    $coe_cats = ['C-Goods Vehicle and Bus', 'Trailers'];
    $vpc_types = ['HV Lot', 'Trailers'];

    // data driver
    $drivers = $this->m_tims->drivers();

    $data = array(
      'header_title'                => 'Vehicle Input Form',
      'vehicle_types'                => $vehicle_types,
      'coe_cats'                     => $coe_cats,
      'vpc_types'                    => $vpc_types,
      'drivers'                     => $drivers,
      'act'                         => set_value('act', 'add'),
      'action'                      => site_url('Master_Tims/vehicle-save'),
      'button'                      => '<i class = "fa fa-save"></i> Save',
      'vehicle_no'                  => set_value('vehicle_no', '', true),
      'vehicle_type'                => set_value('vehicle_type', '', true),
      'description'                 => set_value('description', '', true),
      'year_manufacture'            => set_value('year_manufacture', '', true),
      'engine'                      => set_value('engine', '', true),
      'chasis'                      => set_value('chasis', '', true),
      'iu_label'                    => set_value('iu_label', '', true),
      'registration_date'           => set_value('registration_date', '', true),
      'coe_no'                      => set_value('coe_no', '', true),
      'coe_category'                => set_value('coe_category', '', true),
      'coe_expiry_date'             => set_value('coe_expiry_date', '', true),
      'lifespan_expiry_date'        => set_value('lifespan_expiry_date', '', true),
      'vehicle_inspection_due_date' => set_value('vehicle_inspection_due_date', '', true),
      'road_tax_expiry_date'        => set_value('road_tax_expiry_date', '', true),
      'id_driver'                    => set_value('id_driver', '', true),
      'vpc_no'                      => set_value('vpc_no', '', true),
      'vpc_type'                    => set_value('vpc_type', '', true),
      'vpc_start_date'              => set_value('vpc_start_date', '', true),
      'vpc_end_date'                => set_value('vpc_end_date', '', true),
      'hv_park_no'                  => set_value('hv_park_no', '', true),
      'hv_park_address'             => set_value('hv_park_address', '', true),
      'hv_park_operator'            => set_value('hv_park_operator', '', true),
      'insurance_covered'           => set_value('insurance_covered', '', true),
      'cover_note'                  => set_value('cover_note', '', true),
      'period_insurance_start'      => set_value('period_insurance_start', '', true),
      'period_insurance_end'        => set_value('period_insurance_end', '', true),
      'insurance_cost'              => set_value('insurance_cost', '', true),
    );

    $this->template->display('shipping/Tims/vehicle/vehicle_input', $data);
  }

  public function vehicle_save()
  {
    $data = $this->input->post(null, true);

    $data['registration_date']           = convert_tgl_db_2($data['registration_date']);
    $data['coe_expiry_date']             = convert_tgl_db_2($data['coe_expiry_date']);
    $data['lifespan_expiry_date']        = convert_tgl_db_2($data['lifespan_expiry_date']);
    $data['vehicle_inspection_due_date'] = convert_tgl_db_2($data['vehicle_inspection_due_date']);
    $data['road_tax_expiry_date']        = convert_tgl_db_2($data['road_tax_expiry_date']);
    $data['vpc_start_date']              = convert_tgl_db_2($data['vpc_start_date']);
    $data['vpc_end_date']                = convert_tgl_db_2($data['vpc_end_date']);
    $data['period_insurance_start']      = convert_tgl_db_2($data['period_insurance_start']);
    $data['period_insurance_end']        = convert_tgl_db_2($data['period_insurance_end']);
    $data['createdby']                   = strtoupper($this->session->userdata('userid_1'));
    $data['createddate']                 = date('Y-m-d H:i:s');

    $save = $this->m_tims->insert_vehicle($data);

    if (!$save) {
      $this->session->set_flashdata('message', pesan('Create Vehicle', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Save Vehicle', pesan_sukses()));
    }

    redirect(site_url('Master_Tims/vehicle_input'));
  }

  public function vehicle_edit($id)
  {
    $vehicle = $this->m_tims->get_item_vehicle_detail($id);

    $vehicle_types = ['Goods(Open) Prime Mover', 'Trailers'];
    $coe_cats = ['C-Goods Vehicle and Bus'];
    $vpc_types = ['HV Lot'];

    // data driver
    $drivers = $this->m_tims->drivers();

    $data = array(
      'header_title'                => 'FORM EDIT VEHICLE',
      'vehicle_types'               => $vehicle_types,
      'coe_cats'                    => $coe_cats,
      'vpc_types'                   => $vpc_types,
      'drivers'                     => $drivers,
      'act'                         => set_value('act', 'edit', true),
      'action'                      => site_url('Master_Tims/vehicle-update/' . $id),
      'button'                      => '<i class = "fa fa-save"></i> Update',
      'vehicle_no'                  => set_value('vehicle_no', $vehicle->vehicle_no),
      'vehicle_type'                => set_value('vehicle_type', $vehicle->vehicle_type),
      'description'                 => set_value('description', $vehicle->description),
      'year_manufacture'            => set_value('year_manufacture', $vehicle->year_manufacture),
      'engine'                      => set_value('engine', $vehicle->engine),
      'chasis'                      => set_value('chasis', $vehicle->chasis),
      'iu_label'                    => set_value('iu_label', $vehicle->iu_label),
      'registration_date'           => set_value('registration_date', tgl_ind($vehicle->registration_date)),
      'coe_no'                      => set_value('coe_no', $vehicle->coe_no),
      'coe_category'                => set_value('coe_category', $vehicle->coe_category),
      'coe_expiry_date'             => set_value('coe_expiry_date', tgl_ind($vehicle->coe_expiry_date)),
      'lifespan_expiry_date'        => set_value('lifespan_expiry_date', tgl_ind($vehicle->lifespan_expiry_date)),
      'vehicle_inspection_due_date' => set_value('vehicle_inspection_due_date', tgl_ind($vehicle->vehicle_inspection_due_date)),
      'road_tax_expiry_date'        => set_value('road_tax_expiry_date', tgl_ind($vehicle->road_tax_expiry_date)),
      'id_driver'                   => set_value('id_driver', $vehicle->id_driver),
      'vpc_no'                      => set_value('vpc_no', $vehicle->vpc_no),
      'vpc_type'                    => set_value('vpc_type', $vehicle->vpc_type),
      'vpc_start_date'              => set_value('vpc_start_date', tgl_ind($vehicle->vpc_start_date)),
      'vpc_end_date'                => set_value('vpc_end_date', tgl_ind($vehicle->vpc_end_date)),
      'hv_park_no'                  => set_value('hv_park_no', $vehicle->hv_park_no),
      'hv_park_address'             => set_value('hv_park_address', $vehicle->hv_park_address),
      'hv_park_operator'            => set_value('hv_park_operator', $vehicle->hv_park_operator),
      'insurance_covered'           => set_value('insurance_covered', $vehicle->insurance_covered),
      'cover_note'                  => set_value('cover_note', $vehicle->cover_note),
      'period_insurance_start'      => set_value('period_insurance_start', tgl_ind($vehicle->period_insurance_start)),
      'period_insurance_end'        => set_value('period_insurance_end', tgl_ind($vehicle->period_insurance_end)),
      'insurance_cost'              => set_value('insurance_cost', number_format($vehicle->insurance_cost, 2)),

    );

    $this->template->display('shipping/Tims/vehicle/vehicle_input', $data);
  }

  public function vehicle_update($id)
  {
    $data = $this->input->post(null, true);

    $data['registration_date']           = convert_tgl_db_2($data['registration_date']);
    $data['coe_expiry_date']             = convert_tgl_db_2($data['coe_expiry_date']);
    $data['lifespan_expiry_date']        = convert_tgl_db_2($data['lifespan_expiry_date']);
    $data['road_tax_expiry_date']        = convert_tgl_db_2($data['road_tax_expiry_date']);
    $data['vehicle_inspection_due_date'] = convert_tgl_db_2($data['vehicle_inspection_due_date']);
    $data['vpc_start_date']              = convert_tgl_db_2($data['vpc_start_date']);
    $data['vpc_start_date']              = convert_tgl_db_2($data['vpc_start_date']);
    $data['vpc_end_date']                = convert_tgl_db_2($data['vpc_end_date']);
    $data['period_insurance_start']      = convert_tgl_db_2($data['period_insurance_start']);
    $data['period_insurance_end']        = convert_tgl_db_2($data['period_insurance_end']);
    $data['insurance_cost']              = remove_thousand_separator($data['insurance_cost']);
    $data['updatedby']                   = strtoupper($this->session->userdata('userid_1'));
    $data['updateddate'] = date('Y-m-d H:i:s');

    $update = $this->m_tims->update_vehicle($data, $id);

    if (!$update) {
      $this->session->set_flashdata('message', pesan('Update Vehicle', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Update Vehicle', pesan_sukses()));
    }

    redirect(site_url('Master_Tims/vehicle-edit/' . $id));
  }

  public function vehicle_delete($id)
  {
    $delete = $this->m_tims->delete_vehicle($id);

    if (!$delete) {
      $this->session->set_flashdata('message', pesan('Delete Vehicle', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Delete Vehicle', pesan_sukses()));
    }

    redirect(site_url('Master_Tims/vehicle_information'));
  }



  // -------------------------------------About Customer Transport---------------------

  public function customer_transport()
  {
    $data['message'] = $this->session->flashdata('message');
    $data['list_customer']   = $this->m_tims->get_customer_transport();
    $data['country'] = $this->M_gen_master->get_all('country');

    $this->template->display('shipping/Tims/customer_transport/index', $data);
  }

  function add_customer_transport()
  {
    $country  = $this->M_gen_master->get_all('country');
    $currency  = $this->M_gen_master->get_all('currency');

    $data = array(
      'message'                  => $this->session->flashdata('message'),
      'button'                   => 'Save',
      'action'                   => site_url('Master_Tims/save_customer_transport'),
      'header_title'             => 'Master Tims Customer - Create New',
      'readonly'                 => 'readonly',
      'disable'                  => '',
      'customer_id'              => set_value('customer_id', '', true),
      'customer_name'            => set_value('customer_name', '', true),
      'customer_code'            => set_value('customer_code', '', true),
      'mst_currency'             => $currency,
      'curency_code'              => set_value('curency_code', '', true),
      'address'                  => set_value('address', '', true),
      'mst_country'              => $country,
      'country'                   => set_value('country', '', true),
      'contact_name'             => set_value('contact_name', '', true),
      'fax'                      => set_value('fax', '', true),
      'email'                    => set_value('email', '', true),
      'phone'                    => set_value('phone', '', true),
      'term_payment_due'         => set_value('term_payment_due', '', true),
      'balance_due_date'         => set_value('balance_due_date', '', true),
      'account'                  => set_value('account', '', true),
      'payment_method'           => set_value('payment_method', '', true),
      'submit_value'             => 'Save',
      'is_supplier'              => set_value('is_supplier', '', true),
    );

    $this->template->display('shipping/Tims/customer_transport/input_customer', $data);
  }

  function get_list_item_master()
  {
    $id = $this->input->get("customer_id");

    $data['_isi'] = $this->m_tims->select_allitem($id);

    $this->load->view('shipping/Tims/customer_transport/ajax_item_master', $data);
  }

  function save_customer_transport()
  {
    $data = $this->input->post(null, true);

    $createdby = strtoupper($this->session->userdata('userid_1'));
    $createddate = date('Y-m-d H:i:s');

    $check = $this->input->post('is_supplier');

    if ($check == 'on') {
      $is_supplier = '1';
    } else {
      $is_supplier = '0';
    }

    $data = [
      'customer_id'      => $this->input->post('customer_id', true),
      'customer_name'    => $this->input->post('customer_name', true),
      'customer_code'    => $this->input->post('customer_code', true),
      'curency_code'     => $this->input->post('curency_code', true),
      'address'          => $this->input->post('address', true),
      'country'          => $this->input->post('country', true),
      'contact_name'     => $this->input->post('contact_name', true),
      'fax'              => $this->input->post('fax', true),
      'email'            => $this->input->post('email', true),
      'phone'            => $this->input->post('phone', true),
      'term_payment_due' => $this->input->post('term_payment_due', true),
      'balance_due_date' => $this->input->post('balance_due_date', true),
      'account'          => $this->input->post('account', true),
      'payment_method'   => $this->input->post('payment_method', true),
      'createby'         => $createdby,
      'createddate'      => $createddate,
      'is_supplier'      => $is_supplier,
    ];

    $id = $this->input->post('customer_code', true);

    $exists_in_mst_table = $this->m_tims->cek_mst_table($id);

    if ($exists_in_mst_table) {
      $this->session->set_flashdata('message', pesan('Customer Code already exists', pesan_error()));
    } else {
      $this->m_tims->save_customer_transport($data);
      $this->session->set_flashdata('message', pesan('Save Customer Transport Success', pesan_sukses()));
    }
    redirect(site_url("Master_Tims/add_customer_transport"));
  }

  function Edit_customer_transport()
  {
    $id = $this->input->get("customer_id");
    $data_customer_transport = $this->m_tims->get_id_customer_transport($id);

    $country  = $this->M_gen_master->get_all('country');
    $currency = $this->M_gen_master->get_all('currency');
    $mst_item = $this->m_tims->get_id_customer_transport_dtl($id);

    if (!$id) {
      redirect(site_url('Master_Tims/add_customer_transport'));
    }

    $data = [
      'message'          => $this->session->flashdata('message'),
      'button'           => 'Update',
      'action'           => site_url('Master_Tims/update_customer_transport/' . $id),
      'header_title'     => 'Master Tims Customer - Edit Customer Transport',
      'mst_country'      => $country,
      'mst_currency'     => $currency,
      'mst_item'         => $mst_item,
      'submit_value'     => 'Update',
      'customer_id'      => set_value('customer_id', $data_customer_transport->customer_id),
      'customer_name'    => set_value('customer_name', $data_customer_transport->customer_name),
      'customer_code'    => set_value('customer_code', $data_customer_transport->customer_code),
      'curency_code'     => set_value('curency_code', $data_customer_transport->curency_code),
      'address'          => set_value('address', $data_customer_transport->address),
      'country'          => set_value('country', $data_customer_transport->country),
      'contact_name'     => set_value('contact_name', $data_customer_transport->contact_name),
      'fax'              => set_value('fax', $data_customer_transport->fax),
      'email'            => set_value('email', $data_customer_transport->email),
      'phone'            => set_value('phone', $data_customer_transport->phone),
      'term_payment_due' => set_value('term_payment_due', $data_customer_transport->term_payment_due),
      'balance_due_date' => set_value('balance_due_date', $data_customer_transport->balance_due_date),
      'account'          => set_value('account', $data_customer_transport->account),
      'payment_method'   => set_value('payment_method', $data_customer_transport->payment_method),
      'is_supplier'      => $data_customer_transport->is_supplier,
    ];

    $this->template->display('shipping/Tims/customer_transport/input_customer', $data);
  }

  function update_customer_transport($id)
  {
    $data = $this->input->post(null, true);

    $updatedby = strtoupper($this->session->userdata('userid_1'));
    $updateddate = date('Y-m-d H:i:s');

    $data = [
      'customer_id'              => $this->input->post('customer_id', true),
      'customer_name'            => $this->input->post('customer_name', true),
      'customer_code'            => $this->input->post('customer_code', true),
      'curency_code'             => $this->input->post('curency_code', true),
      'address'                  => $this->input->post('address', true),
      'country'                   => $this->input->post('country', true),
      'contact_name'             => $this->input->post('contact_name', true),
      'fax'                      => $this->input->post('fax', true),
      'email'                    => $this->input->post('email', true),
      'phone'                    => $this->input->post('phone', true),
      'term_payment_due'         => $this->input->post('term_payment_due', true),
      'balance_due_date'         => $this->input->post('balance_due_date', true),
      'account'                  => $this->input->post('account', true),
      'payment_method'           => $this->input->post('payment_method', true),
      'updatedby'                 => $updatedby,
      'updateddate'               => $updateddate
    ];

    $new_customer_code = $this->input->post('customer_code', true);
    $old_customer_code = $this->m_tims->get_customer_code_by_id($id);

    if ($new_customer_code != $old_customer_code) {
      $exists_in_mst_table = $this->m_tims->cek_mst_table($new_customer_code);

      if ($exists_in_mst_table) {
        $this->session->set_flashdata('message', pesan('Customer Code already exists', pesan_error()));
        redirect(site_url("Master_Tims/Edit_customer_transport?customer_id=$id"));
      }
    }

    $this->m_tims->update_customer_transport($data, $id);

    $this->session->set_flashdata('message', pesan('Update Record Success', pesan_sukses()));
    redirect(site_url("Master_Tims/Edit_customer_transport?customer_id=$id"));
  }

  function delete_customer_transport()
  {
    $id = $this->input->get("customer_id");

    $delete_dtl = $this->m_tims->delete_customer($id);

    if (!$delete_dtl) {
      $this->session->set_flashdata('message', pesan('Data Success to delete', pesan_sukses()));
    } else {
      $this->session->set_flashdata('message', pesan('Data Failed to delete', pesan_error()));
    }

    redirect('Master_Tims/customer_transport');
  }

  // -------------------------------------End About Customer Transport---------------------

  //--------------------------------------------------------------------------------------------------------------------------------


  public function item()
  {
    $company   = strtoupper($this->session->userdata('company_id'));
    $data = [
      'message'         => $this->session->flashdata('message'),
      'all_item'        => $this->m_tims->select_allitem(),
      'action'          => site_url('Master_Tims/simpanItem'),
      'List_coa'        => $this->M_vcdn->get_coa_tims($company),
    ];
    

    $this->template->display('shipping/Tims/Item/index', $data);
  }

  function simpanItem()
  {

    $data        = $this->input->post(null, true);
    $Id          = $this->input->post('Id', true);
    $tombol      = $this->input->post('sbt');
    $createdby   = strtoupper($this->session->userdata('userid_1'));
    $createddate = date('Y-m-d H: i: s');

    if ($tombol == 'Save Data') {
      $data = array(
        'Item_number'  => $this->input->post('Item_number', true),
        'Item_name'    => $this->input->post('Item_name', true),
        'Income_coa'   => $this->input->post('Income_coa', true),
        'expenses_coa' => $this->input->post('expenses_coa', true),
        'price2'       => $this->input->post('price_sell', true),
        'price'        => $this->input->post('price_buy', true),
        'gst_type'     => $this->input->post('gst_type', true),
        'Description'  => $this->input->post('Description', true),
        'created_by'   => $createdby,
        'created_date' => $createddate,

      );
      $this->m_tims->save_item($data);
      $msg = "Create Record Success";
    } else {
      $data1 = array(

        'Item_number'  => $this->input->post('Item_number', true),
        'Item_name'    => $this->input->post('Item_name', true),
        'Income_coa'   => $this->input->post('Income_coa', true),
        'expenses_coa' => $this->input->post('expenses_coa', true),
        'income_dept'   => $this->input->post('income_oldcoa', true),
        'expenses_dept' => $this->input->post('expenses_oldcoa', true),
        'price2'       => $this->input->post('price_sell', true),
        'price'        => $this->input->post('price_buy', true),
        'gst_type'     => $this->input->post('gst_type', true),
        'Description'  => $this->input->post('Description', true),
        'updated_by'   => $createdby,
        'updated_date' => $createddate,

      );
      $this->m_tims->update_item($Id, $data1);
      $msg = "Update Record Success";
    }
    $this->session->set_flashdata('message', pesan($msg, pesan_sukses()));
    redirect('Master_Tims/item');
  }

  /* -------------------------------------------------------------------------- */
  /*                              End Master Item                             */
  /* -------------------------------------------------------------------------- */


  /* -------------------------------------------------------------------------- */
  /*                        Master Public Holiday                               */
  /* -------------------------------------------------------------------------- */

  public function public_holiday()
  {
    // $data['holiday'] =  $this->m_tims->public_holiday();
    // $this->template->display('shipping/Tims/public_holiday_list/index', $data);

    $periode = date('Y');
    $data['holiday'] =  $this->m_tims->tampil_get_public($periode);
    // $data['currentYear'] = $currentYear;
    $this->template->display('shipping/Tims/public_holiday_list/index', $data);
  }

  public function public_holiday_add()
  {
    $data = [
      'header_title'    => 'Public Holiday',
      'action'          => site_url('Master_Tims/save_public_holiday'),
      'button'          => 'Save',
      'description'    => set_value('description', '', true),
      'date_holiday'    => set_value('date_holiday', '', true),
    ];

    $this->template->display('shipping/Tims/public_holiday_list/form', $data);
  }

  public function save_public_holiday()
  {
    $data = $this->input->post(null, true);
    $data['date_holiday']     = convert_tgl_db_2($data['date_holiday']);
    $data['createdby'] = strtoupper($this->session->userdata('userid_1'));
    $data['createddate'] = date('Y-m-d H:i:s');

    $save = $this->m_tims->save_public_holiday($data);

    if (!$save) {
      $this->session->set_flashdata('message', pesan('Save Public Holiday', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Add Public Holiday', pesan_sukses()));
    }
    redirect(site_url('Master_Tims/public_holiday'));
  }

  public function public_holiday_edit($id)
  {
    $public = $this->m_tims->public_holiday_by_id($id);

    if (!$public) {
      redirect(site_url('Master_Tims/public-holiday-add'));
    }

    $data = [
      'header_title'    => 'Form Edit Public Holiday',
      'action'          => site_url('Master_Tims/public-holiday-update/' . $id),
      'button'          => 'Update',
      'description'    => set_value('description', $public->description, true),
      'date_holiday'   => set_value('date_holiday', tgl_dmy($public->date_holiday), true),
    ];

    $this->template->display('shipping/Tims/public_holiday_list/form', $data);
  }

  public function public_holiday_update($id)
  {
    $data = $this->input->post(null, true);

    $data['date_holiday']     = convert_tgl_db_2($data['date_holiday']);
    $data['updatedby'] = strtoupper($this->session->userdata('userid_1'));
    $data['updateddate'] = date('Y-m-d H:i:s');
    $update = $this->m_tims->update_public_holiday($data, $id);

    if (!$update) {
      $this->session->set_flashdata('message', pesan('Update Public Holiday', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Update Public Holiday', pesan_sukses()));
    }
    redirect(site_url('Master_Tims/public-holiday-edit/' . $id));
  }

  public function public_holiday_delete($id)
  {
    $delete = $this->m_tims->public_holiday_delete($id);

    if (!$delete) {
      $this->session->set_flashdata('message', pesan('Delete Public Holiday', pesan_error()));
    } else {
      $this->session->set_flashdata('message', pesan('Delete Public Holiday', pesan_sukses()));
    }
    redirect(site_url('Master_Tims/public_holiday'));
  }

  function search()
  {
    $period                  = $this->input->get("period");
    $data['holiday'] = $this->m_tims->tampil_get_public($period);

    $this->template->display('shipping/Tims/public_holiday_list/index', $data);
  }

  /* -------------------------------------------------------------------------- */
  /*                      End Of Master Public Holiday                          */
  /* -------------------------------------------------------------------------- */
}
